name       : xhost
version    : 1.0.7
release    : 5
source     :
    - http://xorg.freedesktop.org/releases/individual/app/xhost-1.0.7.tar.gz : 8dd1b6245dfbdef45a64a18ea618f233f77432c2f30881b1db9dc40d510d9490
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xhost
description: |
    X.Org Applications - xhost
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
