name       : xhost
version    : 1.0.8
release    : 8
source     :
    - https://xorg.freedesktop.org/releases/individual/app/xhost-1.0.8.tar.gz : e5aabce1533dc778ceb5bbc207105cf3770f710629caceaad64675b00c38c3f8
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xhost
description: |
    X.Org Applications - xhost
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xmuu)
    - pkgconfig(xproto)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
